services:
  go-app:
    container_name: go-app
    build: .
    environment:
      DATABASE_DNS: "user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} host=go_db port=${SERVER_PORT} database=${POSTGRES_DB} sslmode=disable"
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:16.3-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: {}