services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 9432
    ports:
      - "9432:5432"