definitions:
  data.Author:
    properties:
      books:
        items:
          $ref: '#/definitions/data.Book'
        type: array
      id:
        type: integer
      name:
        type: string
    type: object
  data.Book:
    properties:
      edition:
        type: integer
      id:
        type: integer
      name:
        type: string
      publication_year:
        type: integer
    type: object
info:
  contact: {}
paths:
  /author:
    get:
      consumes:
      - application/json
      description: list all authors
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/data.Author'
            type: array
      summary: Author
  /book:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/data.Book'
            type: array
      summary: Book
  /book/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Book'
        "404":
          description: Not Found
      summary: Book
swagger: "2.0"
